# Generated by Django 6.0.6 on 2026-06-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_role',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all_rounder', 'All Rounder'), ('wicket_keeper', 'Wicket Keeper')], max_length=50),
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('over', models.DecimalField(decimal_places=1, max_digits=4)),
                ('event_type', models.CharField(choices=[('run', 'Run'), ('wicket', 'Wicket'), ('boundary', 'Boundary'), ('wide', 'Wide'), ('no_ball', 'No Ball'), ('bye', 'Bye'), ('legbye', 'Legbye')], default='run', max_length=50)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('text', models.CharField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='cricket.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchInnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('innings_number', models.PositiveIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='cricket.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('best_bowling', models.CharField(blank=True, max_length=20)),
                ('batting_average', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('strike_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('economy', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ducks', models.PositiveIntegerField(default=0)),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('fifties', models.PositiveIntegerField(default=0)),
                ('hundreds', models.PositiveIntegerField(default=0)),
                ('two_hundreds', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cricket.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
